### ISSUE TITLE
VAF almost zero in pltos

### ISSUE THREAD

**Issue by mpschr** [genome/sciclone#11]
I am not sure what may be going wrong - but the plots dont really display the VAF of the variants. Is anyone experiencing this problem? What may cause it?

Thanks for any hints

```
> head(muts_rel)
  chr     pos ref_reads var_reads        vaf
1   1  894890         6         0 1.00000000
2   1  992846         7         0 1.00000000
3   1 1068848         5         0 1.00000000
4   1 1933035         5         2 0.71428571
5   1 2520872         6        85 0.06593407
6   1 2585425         6        19 0.24000000

> sc = sciClone(vafs=muts_rel,
+               copyNumberCalls=cnasegs_rel, 
+               sampleNames=p.rel, 
+               cnCallsAreLog2 = TRUE, 
+               clusterMethod = 'binomial.bmm',
+               minimumDepth = 50, maximumClusters = 3)
> sc.plot1d(sc,"~/Desktop/clusters.rel.1d.pdf")
```

![clusters rel 1d pdf](https://cloud.githubusercontent.com/assets/1090105/8961619/8a8cf060-3616-11e5-994b-6ec29fdc4ce3.jpg)

**Comment by hartmaier** [comment]
I believe the VAF need to be from 0-100 (not 0-1 like what you have).

**Comment by chrisamiller** [comment]
SciClone expects that VAFs should be expressed as percentages, not fractions. Multiply your VAF column by 100 and you should be set.

**Comment by mpschr** [comment]
Yes, now it works
