### ISSUE TITLE
What is inadequate depth?

### ISSUE THREAD

**Issue by mpschr** [genome/sciclone#12]
I am learning to run sciclone with a sample pair from the same patient. I have done the CNA with copywriteR and have the log2-segmented-values as input (as also specified by `cnCallsAreLog2=TRUE`).

First, I observed that the algorithm discards the majority of the variants due to inadequate depth. How is inadequate depth defined - what are the margins? Are there any recommendations on how I can better prepare the input data? 

Secondly, even more variants are discarded when doing a joint analysis - is this because a 'adequate' depth is required for both samples?

Thanks already for any explanations! Here below the details of my input.

Best,
Michael

initial diagnosis sample
```
104 sites (of 850 original sites) are copy number neutral and have adequate depth in all samples
12 sites (of 850 original sites) were removed because of copy-number alterations
745 sites (of 850 original sites) were removed because of inadequate depth
746 sites (of 850 original sites) were removed because of copy-number alterations or inadequate depth
```

relapse
```
158 sites (of 972 original sites) are copy number neutral and have adequate depth in all samples
13 sites (of 972 original sites) were removed because of copy-number alterations
809 sites (of 972 original sites) were removed because of inadequate depth
814 sites (of 972 original sites) were removed because of copy-number alterations or inadequate depth
```

joint run 
```
27 sites (of 1658 original sites) are copy number neutral and have adequate depth in all samples
1500 sites (of 1658 original sites) were removed because of copy-number alterations
1631 sites (of 1658 original sites) were removed because of inadequate depth
1631 sites (of 1658 original sites) were removed because of copy-number alterations or inadequate depth
```

here is a histogram of the segmeans values (log2) as obtained from copywriteR 
![segmeans](https://cloud.githubusercontent.com/assets/1090105/8980612/4d0a80a8-36b2-11e5-8186-12f1aa4d4df9.png)

**Comment by mpschr** [comment]
Hi,

I realized that the inadequate depth is dependent on the `minimumDepth` parameter. I overlooked this obvious fact and understood that something with the segmented data was wrong. Sorry for the confusion - closing issue

**Comment by chrisamiller** [comment]
Yep, you've got it - the minimumDepth parameter is what you want here. You'll have better results if you can obtain data with higher depth, though. The rightmost figure in this poster shows why - sampling error creates a large amount of spread in clusters at low depths, meaning that subclones will be harder to tease apart.   http://figshare.com/articles/aacrCancer_aml31_2015_02_pdf/1304601  Best of luck!
