### ISSUE TITLE
Running sciClone on cell prevalence (CP) data

### ISSUE THREAD

**Issue by ikramu** [genome/sciclone#13]
Hi,

As I understand, sciClone uses estimates of variant allele frequency (VAF) in copy-neutral regions to estimate subclonality (thus, in a manner, not using CNV info; please correct me if I am wrong).

The exome sequencing data I have got has relatively fewer mutations with higher variation in copy number across the genome. When I remove the non-neutral copy number regions (copy number != 2), I am left with very few mutations. Given that I have 5 or more samples for each case, the resulting VAF matrix becomes very sparse leading to poor results. 

I was wondering if I can complement the VAF with copy number and ploidy to compute cancer cell fraction (http://www.nature.com/leu/journal/v28/n1/fig_tab/leu2013248f1.html#figure-title) or, alternatively, compute cell prevalence values using PyClone or ASCAT, and feed that into sciClone. Will sciClone clustering work as it does when using VAFs? If yes, that's excellent; if not, can you recommend some alternative tool for subclonal reconstruction. 

Thanks,
Ikram

**Comment by chrisamiller** [comment]
Hi Ikram, I responded to your question over on Biostars, so I'll resolve this. Feel free to ask followups in that thread: https://www.biostars.org/p/177444/
