### ISSUE TITLE
Plotting code for Fig3b, 3c

### ISSUE THREAD

**Issue by daviddliu** [genome/sciclone#17]
Hi, I'm trying to plot the posterior density as shown in Figures 3b and 3c. However, I cannot figure out what the posterior for each cluster should be given (alpha, beta, mu, nu). I was wondering if you could point me to an explicit formulation for the posterior, either in your paper or the Ma paper. Even better would be the code that you used to make the figure.

Thanks!

**Comment by chrisamiller** [comment]
The data and scripts need to reproduce the figures from the paper are all
in the sciclone-meta repository. Specifically, for figure 3, you'll want:
https://github.com/genome/sciclone-meta/tree/master/manuscript/data/figure3

**Comment by daviddliu** [comment]
Ah perfect, thanks.
