### ISSUE TITLE
tumor purity 

### ISSUE THREAD

**Issue by crazyhottommy** [genome/sciclone#21]
Hi,

Thanks for this tool. I was wondering how sciclone takes into account of tumor purity when inferring clonal events. I saw this commits that you removed it https://github.com/genome/sciclone/commit/e60f6b793c2151a639864e3aab6fe1ea0c66975c

Now, I have tumor purity calculated from other tools such as ESTIMATE, ABSOLUTE and Sequenza.
How should I use it in the context of sciclone?

Thanks!
Tommy

**Comment by chrisamiller** [comment]
Sciclone does not use that information at all. There was some code stubbed
in at one point that we were playing with, but it never performed well
enough to use.  Bottom line, the clustering algorithm doesn't care about
purity. You can scale your VAFs beforehand, or scale your plots/VAFs
afterwards, and the results will be roughly comparable.

**Comment by crazyhottommy** [comment]
good to know that!
Thanks.
