### ISSUE TITLE
Incorporating CNA events

### ISSUE THREAD

**Issue by kippakers** [genome/sciclone#22]
Hi, I'm curious if your suggested strategy for incorporating CNA variants into a clonality analysis has changed since the the Sciclone paper in 2014.  I'm looking to assign clone numbers to mutations from tumor samples using sciclone but I don't want to exclude variants in CNA regions.   

Is it reasonable to simply "adjust" a VAF directly by the copy number of that variant?  
ie VAFnew = VAF/(CN/2)

**Comment by chrisamiller** [comment]
It's not as simple as just adjusting - here's an explanation of why: https://www.biostars.org/p/106774/#106834

At present, the strategy is still to exclude those regions. Other algorithms exist that try to assign these points, but I don't have enough experience with them to comment on their effectiveness at this time.

**Comment by kippakers** [comment]
Thanks for the info!
