### ISSUE TITLE
can't do clustering

### ISSUE THREAD

**Issue by nesilin** [genome/sciclone#23]
Hi!

I'm trying to run SciClone for a WGS sample (7476 SNV). For the cna calling of this sample  I do not have log2 segment mean values but rather 0,1,2 or 3  from Control-FREEC 9.1 software. Therefore, I only have the segments aberrant ploidy but not diploid segments. However, according to the documentation SciClone assumes that mutations that are not within those altered segments are diploid and gives a cn of 2.

segments file as copyNumberCalls dataframe is :
```
  chromosome    start      end cn
1          9 21900000 22000000  1
2         12 66450000 66500000  0
3         20 47350000 47500000  3
```
When I tried to run SciClone like this: 
```

sc <- sciClone(vafs=vafs, copyNumberCalls=copyNumberCalls, regionsToExclude=NULL,
                 sampleNames=id_pat, minimumDepth=0, clusterMethod='bmm',
                 clusterParams="no.apply.overlapping.std.dev.condition",
                 cnCallsAreLog2=FALSE, useSexChrs=FALSE, doClustering=TRUE,
                 verbose=TRUE, 
                 copyNumberMargins=NULL, maximumClusters=15,
                 annotation=NULL, doClusteringAlongMargins=TRUE,
                 plotIntermediateResults=0)

```
I got the following error:

```
[1] "checking input data..."
[1] "Not all variants fall within a provided copy number region. The copy number of these variants is assumed to be 2."
can't do clustering - no copy number 2 regions to operate on in sample 1 
```
Then I decided to download the chromosome lengths like it was suggested here (https://www.biostars.org/p/16396/ ): 
```
$ curl -s ftp://hgdownload.cse.ucsc.edu/goldenPath/hg19/database/chromInfo.txt.gz | gunzip -c 
```
And complete the copyNumberCalls data frame with the missing segments like this:

```
   chromosome    start       end cn
4           1        0 249250621  2
5           2        0 243199373  2
6           3        0 198022430  2
7           4        0 191154276  2
8           5        0 180915260  2
9           6        0 171115067  2
10          7        0 159138663  2
11          8        0 146364022  2
1           9 21900000  22000000  1
12          9        0  21899999  2
13          9 22000001 141213431  2
14         10        0 135534747  2
15         11        0 135006516  2
2          12 66450000  66500000  0
16         12        0  66449999  2
17         12 66500001 133851895  2
18         13        0 115169878  2
19         14        0 107349540  2
20         15        0 102531392  2
21         16        0  90354753  2
22         17        0  81195210  2
23         18        0  78077248  2
24         19        0  59128983  2
3          20 47350000  47500000  3
25         20        0  47349999  2
26         20 47500001  63025520  2
27         21        0  48129895  2
28         22        0  51304566  2

```
And then I've tried to run SciClone again and still got the same error. 

I cannot provide the SNV mutation calling file because of confidentiality issues. But it has low coverage and as I mentioned before there are a lot of mutations (7476 SNV). 

I'm aware I am running SciClone with min depth of 0 which is definitely not recommended but I also tried to run it with at least 10 of min depth and still got the same error. 

I also checked whether this is a data type issue but I do not think is the case...

```
sapply(copyNumberCalls, class)
 chromosome       start         end          cn 
"character"   "integer"   "integer"   "numeric" 
```

```
sapply(vafs, class)
 chromosome    position   ref_reads   var_reads         vaf 
"character"   "integer"   "integer"   "integer"   "numeric"
```
I would be grateful if you could give me some clue about this error.

**Comment by chrisamiller** [comment]
Does your reference match between all your files? (chr1 and 1 are not the same thing)

**Comment by nesilin** [comment]
I 've already checked and this is not the case...

**Comment by chrisamiller** [comment]
1) You shouldn't need to add any extra segments of copy number 2 - sciclone will make that assumption, as you've noted.

2) The message you posted above is not an error, it's just a warning, and sciclone should have continued to run. Can you paste the full output of the command?

3) If you use a minimum depth of zero, your results will likely be garbage.  See figure 5 here for a graphical explanation of why: http://www.cell.com/action/showImagesData?pii=S2405-4712%2815%2900113-1  Even 10x minimum depth is going to severely limit your ability to detect subclonal variants.  I'd recommend going no lower than 20, if you're working with 30x whole-genome data.

**Comment by nesilin** [comment]
2. The complete output is the one above. I think is an error because the process stops after printing this message. If I change the parameter doClustering from TRUE to FALSE it reports the following: 
```
[1] "checking input data..."
[1] "Not all variants fall within a provided copy number region. The copy number of these variants is assumed to be 2."
can't do clustering - no copy number 2 regions to operate on in sample 1 
8373 sites (of 8729 original sites) are copy number neutral and have adequate depth in all samples
136 sites (of 8729 original sites) were removed because of copy-number alterations
221 sites (of 8729 original sites) were removed because of inadequate depth
356 sites (of 8729 original sites) were removed because of copy-number alterations or inadequate depth
```

**Comment by chrisamiller** [comment]
It appears as though the process is completing just fine, then! You should have a variable named "sc" that contains your results. You can write them to a file or plot them using the other commands, as in the example. (writeClusterTable and sc.plot1d). Does that not work?

**Comment by nesilin** [comment]
The sc object with the results is empty because after the message the program stops. It took less than one minute to be printed in the terminal/console.  I will try to prepare some example with synthetic data with the same problem and I will send it to you. Maybe that helps.

**Comment by chrisamiller** [comment]
Yes, that would definitely help.

**Comment by nesilin** [comment]
Hi Chris!
I've tried to run SciClone with a different dataset (a sample form the TCGA/Pan Can Atlas Project freeze1.3)  and I obtained the same error.  I do no have permissions to send you the data but If you have access to data of the Pan Can Atlas I 've tried to run SciClone with the sample TCGA-06-5416 with GBM cancer. This patient has a lot of mutations so it resembles to my  data. I've attached part of the R script where I prepared the data frames for SciClone. Notice that from the raw datasets of the Pan Can Atlas project I have divided it by cancer type and patient and I've added a column patient to the maf file of each patient as well as filtered out the normal segmented data of the segmented data set (I did not use the cna GISTIC calls but the segmented data of the http://firebrowse.org/). 

```
################################### FUNCTIONS ################################

calc_vafs <- function(x, y) {
  vaf = (x/(x+y))*100
  return(vaf)
}

cnabs <- function(x) {
  cn<-(2^x)*2
  return(cn)
}

############################### LIBRARIES USED ################################

library(sciClone)
library(devtools)
library(dplyr)


########################## LOADING AND PREPARING DATA FRAMES #####################

id_pat = 'TCGA-06-5416'
data_file = ' ' #path to the directory with the mutation.maf file and segments.txt file 
                    #of that sample

mut_file = paste(data_file, id_pat, 'mutation.maf', sep="/")
seg_file = paste(data_file, id_pat, 'segments.txt', sep="/")

## First dataframe 'vafs'

data = read.table(mut_file, header=T)

# Previously, from the Tumor_Sample_Barcode I have obtained the patient barcode. 
# That's why in the maf file there is a column called patient. 

vafs <- data[ , c('Chromosome', 'Start_Position', 't_ref_count', 
't_alt_count', 'Tumor_Sample_Barcode', 'Hugo_Symbol', 'patient')]
names(vafs) <- c('Chromosome', 'Position', 'Ref_Count',
 'Alt_Count', 'Tumor_Sample_Barcode', 'Hugo_Symbol', 'Patient')

rm('data')

# Calling calc_vafs to calculate the variant allele frequency for each mutation.

vafs$Var_freq <- mapply(vafs$Alt_Count, vafs$Ref_Count, FUN=function(x, y) calc_vafs(x, y))

## Second dataframe 'copyNumberCalls'

# Previously, from the Tumor_Sample_Barcode I filtered out the 
# segments of normal sample according to https://wiki.nci.nih.gov/display/TCGA/TCGA+barcode 
# and then dividing the dataset by patient. 

copyNumberCalls <- read.table(seg_file, header = T)

# Calling cnabs to convert log values to absolute values
copyNumberCalls$'cn'<-as.numeric(lapply(copyNumberCalls$'Segment_Mean', 
FUN=function(x) cnabs(x)))

# subsetting into the wanted list of dataframes

vafs<-vafs[, c('Chromosome', 'Position', 'Ref_Count', 'Alt_Count', 'Var_freq')]
copyNumberCalls <- copyNumberCalls[, c('Chromosome', 'Start', 'End', 'cn')]

# sorting by chromosome column

vafs <- vafs[order(vafs$Chromosome),]
copyNumberCalls <- copyNumberCalls[order(copyNumberCalls$Chromosome),]

# Run SciClone 
sc <- sciClone(vafs=vafs, copyNumberCalls=copyNumberCalls, 
               regionsToExclude=NULL,sampleNames=id_pat, 
               minimumDepth=20, clusterMethod='bmm',
               clusterParams="no.apply.overlapping.std.dev.condition",
               cnCallsAreLog2=FALSE, useSexChrs=FALSE, doClustering=TRUE,
               verbose=TRUE, 
               copyNumberMargins=NULL, maximumClusters=15,
               annotation=NULL, doClusteringAlongMargins=TRUE,
               plotIntermediateResults=0)

```
I've tried the same for R-3.3.0 and R-3.3.1 and in both I have installed sciClone 1.1.0.  I hope this is not a problem of versions... 

```
> sessionInfo()

R version 3.3.1 (2016-06-21)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.10

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=es_ES.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=es_ES.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=es_ES.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=es_ES.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
 [1] grid      stats4    parallel  stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] dplyr_0.5.0         devtools_1.12.0     sciClone_1.1.0      TeachingDemos_2.10  MKmisc_0.993       
 [6] plotrix_3.6-3       RColorBrewer_1.1-2  rgl_0.96.0          bmm_0.3.1           NORMT3_1.0-3       
[11] ggplot2_2.2.0       IRanges_2.8.0       S4Vectors_0.12.0    BiocGenerics_0.20.0

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.8       DEoptimR_1.0-6    plyr_1.8.4        tools_3.3.1       digest_0.6.10     jsonlite_1.1     
 [7] memoise_1.0.0     tibble_1.2        gtable_0.2.0      shiny_0.14.2      DBI_0.5-1         withr_1.0.2      
[13] knitr_1.15        htmlwidgets_0.8   robustbase_0.92-6 R6_2.2.0          magrittr_1.5      scales_0.4.1     
[19] htmltools_0.3.5   assertthat_0.1    mime_0.5          colorspace_1.2-7  xtable_1.8-2      httpuv_1.3.3     
[25] lazyeval_0.2.0    munsell_0.4.3  
```
Thank you in advance!

**Comment by chrisamiller** [comment]
Can you post the head() of the copyNumberCalls and vafs data frames just
before sciClone is run?

(There is no issue with sharing any of that info - the TCGA somatic
mutations are public access - it's only the germline muts that are
restricted)

**Comment by nesilin** [comment]
Hi Chris!!

I think I found the problem. As I was using integer values as the copy number estimations I set the parameter copyNumberMargins to NULL or 0 because, for example, 0.25 make no sense as the values where 1, 2, 3 ... So, when I tried to run any type of dataset with NULL or 0 the error mentioned above appeared whereas running it with 0.25 seems to make SciClone work. I would be grateful if you can confirm that and I will close the issue. 

Thanks!

**Comment by chrisamiller** [comment]
Yep, that'll do it. To be clear, the copyNumberMargins parameter sets the boundaries for what is considered copy number neutral, since CN data typically contains some noise. The default of 0.25 means that it'll accept between 1.75 and 2.25 as CN2.  Setting it to NULL is a bad idea :)  Glad you figured it out!
