### ISSUE TITLE
Install hang and manual build trouble

### ISSUE THREAD

**Issue by tedtoal** [genome/sciclone#25]
My R on my Macbook hung while installing sciClone, after displaying the message "** preparing package for lazy loading".

I then decided to build it myself manually, and followed the instructions, but the command:

R CMD build sciClone

gave the error message: cannot change to directory ‘sciClone’

I eventually realized the problem was that I cloned the sciClone repository by downloading the zip file, and this created directory "sciclone-master" rather than sciclone, and I had already changed into that directory, and was able to build with:

R CMD build .

So, to avoid confusion, you might change the README file to spell it out:

R CMD build <directory with cloned sciClone repository>

e.g.

R CMD build sciclone
or perhaps:
R CMD build sciclone-master
or if you are in the directory already:
R CMD build .

Finally, after I was able to run the 'build' successfully, I tried installing with:

R CMD INSTALL sciClone_1.1.0.tar.gz

and once again it hung while preparing package for lazy loading:

    * installing to library ‘/Library/Frameworks/R.framework/Versions/3.3/Resources/library’
    * installing *source* package ‘sciClone’ ...
    ** R
    ** preparing package for lazy loading

**Comment by chrisamiller** [comment]
Not sure how to reproduce this - seems to work just fine on my macbook:

```
$ git clone git@github.com:genome/sciclone.git
Cloning into 'sciclone'...
remote: Counting objects: 929, done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 929 (delta 2), reused 0 (delta 0), pack-reused 923
Receiving objects: 100% (929/929), 14.12 MiB | 3.84 MiB/s, done.
Resolving deltas: 100% (478/478), done.
Checking connectivity... done.
$ R CMD build sciclone
* checking for file ‘sciclone/DESCRIPTION’ ... OK
* preparing ‘sciClone’:
* checking DESCRIPTION meta-information ... OK
* checking for LF line-endings in source and make files
* checking for empty or unneeded directories
* building ‘sciClone_1.1.0.tar.gz’

$ R CMD INSTALL sciClone_1.1.0.tar.gz
* installing to library ‘/Library/Frameworks/R.framework/Versions/3.3/Resources/library’
* installing *source* package ‘sciClone’ ...
** R
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
* DONE (sciClone)
```
