### ISSUE TITLE
Problem including copynumber data into Sciclone clustering for WES

### ISSUE THREAD

**Issue by Marco0107** [genome/sciclone#26]
Hi,
Can anyone help?
I'm using Sciclone since few weeks ago and now I want to include copynumber file into clustering.
Copynumber calls were made by VarScan2 and segmentation by DNAcopy accordingly VarScan parameters:
dkoboldt.github.io/varscan/copy-number-calling.html#copy-number-caller 

However, the segment_mean values from my copynumber input (generated by DNAcopy) is quite different from the one at sciclone-meta, ranging from ~15 to ~35 instead of 0 to ~3

Here's the head of my copynumber.dat: 
> 1	13377	13677	42.025
1	13777	721826	22.5625
1	721926	1190560	15.7044
1	1190660	1197650	23.7857
1	1197686	1580647	16.5196
1	1581343	1582332	30.28
1	1585595	1588914	21.825

> 

Should I make some processing before loading into Sciclone?

Thanks,

Marco

**Comment by chrisamiller** [comment]
Yes, it appears that something went very wrong with your copy number
calling. I'm afraid I can't help troubleshoot that step, but it does seem
like that's where your problem is. Best of luck!
