### ISSUE TITLE
CCF value in sciclone

### ISSUE THREAD

**Issue by snoopy-448** [genome/sciclone#27]
HI
I am running sciclone on just one sample. I want to get the ccf for each mutation, but cannot find it in the output file generated by writeClusterTable. Could you tell me where to find ccf values?

Thank you very much !

Yang

**Comment by chrisamiller** [comment]
SciClone does not calculate CCF. It excludes copy number altered points, and the expectation is thus that each point's VAF should be half of it's cellular fraction.  Best of luck
