### ISSUE TITLE
how integrate CNV results into clonal evolution by sciclone

### ISSUE THREAD

**Issue by moshl** [genome/sciclone#29]
Hi, Chrisamiller. 
I carefully read your paper about sciclone. But i am confused how to add CNVs into clones. your paper has a simply description: THetA was used to detect clonal and subclonal copy-number events in a multiple myeloma sample, then converted to pseudo-VAFs and co-clustered with SNV data using SciClone. 
**So, Firstly how to converted CNV results from THetA to preudo-VAFs? 
secondly, if the CNVs are domaint, the preudo-VAFs are 0.5? 
Thirdly, if the SNVs locate into the CNV regions, why we excluded them when we run sciClone?** 
looking forward to your apply. Thanks
Shanlan

**Comment by chrisamiller** [comment]
Most of these questions have already been answered on biostar.  I'd suggest reading through those first, and then if you have more detailed questions. feel free to follow up with another question.  Best of luck!  https://www.biostars.org/t/sciclone/

**Comment by moshl** [comment]
Thank Chris. I read some questions related with my interestings. Although i donnot find the detailed algorithm to solve pseudo-VAF, I guess i understand it.  for example, the SNV1 located in a CN-LOH region, its' VAF is 0.9. SNV1 has a expected vaf 0.45, which repress the pseudo-VAF of the CN-LOH. Is it right?

**Comment by chrisamiller** [comment]
Yep - you've got the right idea.  There are other tools now available that attempt to explicitly perform this correction and assign CCFs to individual variants. This is a more complicated procedure. SciClone is explicitly designed to remain simple and just skip those variants, which has its pros and cons.
