### ISSUE TITLE
how to solve the bias of clusters

### ISSUE THREAD

**Issue by moshl** [genome/sciclone#30]
hi, chris. 
Now, I have converted some CNV to pseudo-VAF. And I combined the SSM with pseudo-VAF for clonal analysis by Sciclone. I always get 3 clones by different maxmumClusters (see fig as below). But I think some clusters should be separeted into 2 clusters. For example, cluster2 included some low-VAF SSM and high-VAF, the high-VAF should be specific domaint clone at R7 and the low-VAF should be belong to it. So, do we seperated them into two clusters by myself?  Looking forward to your apply. Thanks.

P.s. The data from 30X WGS, the minmumDepth=10. I improve the mimDepth:20, then I get same results)

![1539329321 1](https://user-images.githubusercontent.com/29252072/46854617-04dcca80-ce34-11e8-8730-0336f7716943.jpg)

**Comment by chrisamiller** [comment]
Your ability to resolve clusters is fundamentally limited by your depth of sequencing. At some point, sampling error drowns out much of the signal. See figure 5 here for a detailed example: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4669575/#!po=1.72414

Trying to do anything more than a rough outline of clonal structure from wgs data just isn't feasible in many situations.
