### ISSUE TITLE
Possible bias related to tumour purity?

### ISSUE THREAD

**Issue by lajoimat** [genome/sciclone#31]
Hello,

I would like to know if purity affects the ability of SciClone to identify subclones in solid tumors. In other words, does SciClone tends to report more subclones in high purity samples than in low purity samples, assuming the true number of subclones is the same? 

Thank you

**Comment by chrisamiller** [comment]
All other things being equal (like sequencing depth), then yes, of course purity affects the ability to distinguish individual subclones. Given, say 100x sequencing depth, the difference between 25% and 50% VAF is probably significant, but the difference between 10% and 20% VAF is well within the bounds of the error bars on each individual point.  Very high sequencing depth can help overcome this - see Figure 5 in this paper for an illustration: https://www.ncbi.nlm.nih.gov/pubmed/26645048 (as well as the supplemental animation of that plot).
