### ISSUE TITLE
Error in .normargSEW0(start, "start") error

### ISSUE THREAD

**Issue by Shawnmhy** [genome/sciclone#32]
I am using SciClone to treat my own data but I got the following error message:

> Error in .normargSEW0(start, "start") : 
  'start' must be a numeric vector (or NULL)

My vafs file and copy number file look like:
<img width="538" alt="WeChat293ffa70c7770587d03102b4c9d2585b" src="https://user-images.githubusercontent.com/36376322/55660876-822b3b80-57d6-11e9-9ca1-0a68de9696a0.png">
<img width="302" alt="WeChat36af60fce12ba2c1b92d80f7102e297d" src="https://user-images.githubusercontent.com/36376322/55660904-a25afa80-57d6-11e9-8d8a-eb6414040828.png">
Why is this error occur?

**Comment by chrisamiller** [comment]
Try removing the header line from your VAF file

**Comment by Shawnmhy** [comment]
> Try removing the header line from your VAF file

But the VAF file in your example also has header line.

**Comment by chrisamiller** [comment]
Possibly the CN file, then?  I'm away today, and can't verify, but I recall that headers on one of the input files can have that effect. If that doesn't solve it, let me knoe

**Comment by Shawnmhy** [comment]
Neither my CN file nor VAF file has headers but the error is still there...

**Comment by Shawnmhy** [comment]
ok now the error is gone, but when I delete headers another issue came:

Error in cleanAndAddCN(vafs[[i]], copyNumberCalls[[i]], i, cnCallsAreLog2,  :

**Comment by Shawnmhy** [comment]
I am just running one sample, but seems like I also need to proved other two samples:

[1] "ERROR: column st  in sample 2 is not numeric"

**Comment by chrisamiller** [comment]
Were you able to figure this out?  If so, I'm going to resolve this issue - thanks

**Comment by jfass** [comment]
> I am just running one sample, but seems like I also need to proved other two samples:
> 
> [1] "ERROR: column st in sample 2 is not numeric"

@Shawnmhy how did you address the "column st  in sample 2 is not numeric" error? I'm also using a single sample at a time (no multi-sequenced tumors), and I'm getting this error.

**Comment by chrisamiller** [comment]
Try removing any non-numeric characters (including headers) from your input list.
