### ISSUE TITLE
Not all mutations are clustered

### ISSUE THREAD

**Issue by Shawnmhy** [genome/sciclone#33]
Hi Miller.
I use SciClone to test my own data. I run ten samples at a time and each sample contains ~100 mutations. But the result only returns two clusters and certain mutations are dropped, which means many of them do not belong to any clusters...
How to explain this result? do you have any ideas?

**Comment by chrisamiller** [comment]
Sciclone requires that all mutations exceed the minimumDepth parameter in all samples, which is a frequent source of this kind of issue.  It also requires that mutations be CN-neutral in all samples, which can be a problem if your CN calling is particularly noisy (or your sample is particularly instable).  Looking at your output file can help you determine which sample(s) or calls are the problem.

**Comment by Shawnmhy** [comment]
Hi Miller.
Thank you for the reply. I guess the minimumDepth issue is the case. But why is this requirement so important to Sciclone in terms of accuracy?
And what if some of mutations in my sample are not CN-neutral? will they be just simply be ignored or there is other kind of impact on final results?

**Comment by chrisamiller** [comment]
A lot of these questions have already been answered, either in the paper or on Biostar (https://www.google.com/search?q=site%3Abiostars.org+sciclone)

Briefly: SciClone works best with deep readcounts, as they decrease the uncertainty associated with each VAF. See Figure 5 of this paper for an example of how low readcounts add noise and uncertainty http://www.cell.com/cell-systems/fulltext/S2405-4712(15)00113-1 

For problems with CN - see this answer
https://www.biostars.org/p/106774/#106834

Best of luck!
