### ISSUE TITLE
Description for sciClone@vafs.merged

### ISSUE THREAD

**Issue by jgarces02** [genome/sciclone#35]
Hi (again) @chrisamiller, 

If you please, I've got a (basic) question about `sciClone` outputs, specifically about the `sciClone@vafs.merged` data frame.
```
  chr        st 545_D.ref 545_D.var 545_D.vaf 545_D.cn 545_D.cleancn 545_D.depth
1   1  22987700        27         7 0.2058824        2             2        3400
2   1  22987701        28         7 0.2000000        2             2        3500
3   1  47548113        19         3 0.1363636        2             2        2200
```
 What are *cn cols, please? I've read the code but I'm not able to identify them.

Thanks again for your help.

**Comment by chrisamiller** [comment]
for each sample, it lists:
- the numeric copy number (as reported in the input file), 
- the integer copy number (as assigned by sciclone, using the CN margins)

**Comment by jgarces02** [comment]
Perfect! Thanks a lot!
