### ISSUE TITLE
2D plot doesn't show all clusters 

### ISSUE THREAD

**Issue by Wan-Yifei** [genome/sciclone#37]
Hi Chris,

I found the 2D result doesn't show all clusters. In the below image, it only appears cluster# 1, 4, 6.

![image](https://github.com/Wan-Yifei/AH_BioPharma/blob/master/sciClone/test/test_result.PNG?raw=true)

My code is:
```
# sample_01 vs sample_03
sc1_3 = sciClone(vafs=list(v1,v3),
              copyNumberCalls=list(cn1,cn3),
              sampleNames=names[c(1,3)],
              cnCallsAreLog2=TRUE,
              minimumDepth=5)
#              regionsToExclude=reg1)


writeClusterTable(sc1_3, "../results/D-01-01_D-01-03_SciClone.2d")
sc.plot2d(sc1_3,"../results/D-01-01_D-01-03_SciClone.2d.pdf")
```

The first lines of my input:
```
> head(v1)
  V1        V2  V3 V4   V5
1  1  16956761  33  5 13.2
2  1  17215684 201  8  4.7
3  1  36202125  71 14 14.7
4  1 120594740  48  6 13.3
5  1 143282519  31  4 10.3
6  1 145296448 103  5  5.7

> head(v3)
  V1       V2  V3 V4   V5
1  1  9776429  38  4 10.3
2  1 16908892  21  3 12.5
3  1 16908894  21  3 12.5
4  1 16910063 195 15 10.0
5  1 16914393  33  6 13.3
6  1 16956761  26  7 21.2

> head(cn1)
  V1        V2        V3       V4
1  1     14597  53236566 2.262630
2  1  53237847  53238074 0.535404
3  1 121351809 121482587 0.810228
4  1 143278556 143744052 0.885952
5  1 144598400 148247541 2.157410
6  1 152079714 153507465 1.991010

> head(cn2)
  V1        V2        V3       V4
1  1     14597  53236566 2.308250
2  1  53237847  53238163 0.762231
3  1 121351809 143537963 0.956697
4 10     93083  38736684 2.321730
5 10  39078787  42817808 0.814677
6 10  47708884  49245684 1.852790
```

Is there any way to show all clusters?

Thanks,
Yifei

**Comment by chrisamiller** [comment]
Without more information, I can't answer that question.  I'd have to know what your inputs are, what parameters you've used, etc, to be able to offer any useful advice.

**Comment by Wan-Yifei** [comment]
> Without more information, I can't answer that question. I'd have to know what your inputs are, what parameters you've used, etc, to be able to offer any useful advice.

Dear Chris,

I have updated my question. 

Thanks,
Yifei

**Comment by chrisamiller** [comment]
When you look at your output table, how many points are assigned to a cluster?  

Also, it doesn't look to me like your CN files are log2, even though you have set `cnCallsAreLog2=T`

**Comment by chrisamiller** [comment]
Also, what's the output from running your command? It should give you a # of points in CN-neutral regions with adequate depth as part of that output.

**Comment by Wan-Yifei** [comment]
> When you look at your output table, how many points are assigned to a cluster?
> 
> Also, it doesn't look to me like your CN files are log2, even though you have set `cnCallsAreLog2=T`

I forgot that I have done `cn1$segment_mean <- 2^(cn1$seg.mean+1)` according to your suggestion on Biostar. Thus, I correct the `cnCallsAreLog2` as `F` and rerun.

> Also, what's the output from running your command? It should give you a # of points in CN-neutral regions with adequate depth as part of that output.

The # of points:
```
[1] "checking input data..."
[1] "Not all variants fall within a provided copy number region. The copy number of these variants is assumed to be 2."
[1] "Not all variants fall within a provided copy number region. The copy number of these variants is assumed to be 2."
225 sites (of 249 original sites) are copy number neutral and have adequate depth in all samples
20 sites (of 249 original sites) were removed because of copy-number alterations
4 sites (of 249 original sites) were removed because of inadequate depth
24 sites (of 249 original sites) were removed because of copy-number alterations or inadequate depth
```

I also check the # of points of each cluster:
```
$ awk -F"\t" 'NR>1{print $16}' D-01-01_D-01-03_SciClone.2d | sort | uniq -c
      3 1
      5 2
     93 3
    124 4
     24 NA
```
It looks all clusters have more than 2 points. But when I check the 2d plot. It only appears cluster#1 and 3.

![](https://raw.githubusercontent.com/Wan-Yifei/AH_BioPharma/master/sciClone/test/test_result2.PNG)

Thanks!

**Comment by chrisamiller** [comment]
Hrmm, okay. Can you attach your output table?

**Comment by Wan-Yifei** [comment]
> Hrmm, okay. Can you attach your output table?

Please see attached:
https://github.com/Wan-Yifei/AH_BioPharma/blob/master/sciClone/test/D-01-01_D-01-03_SciClone.2d

**Comment by chrisamiller** [comment]
Something has gone very wrong there.  I suspect that you have not "merged" your readcounts.  your input files need to have readcounts for each variant in each sample.  See  https://www.biostars.org/p/118083/#118087 for details.

**Comment by Wan-Yifei** [comment]
> Something has gone very wrong there. I suspect that you have not "merged" your readcounts. your input files need to have readcounts for each variant in each sample. See https://www.biostars.org/p/118083/#118087 for details.

Thanks for figuring out it.

I will merge my SNV file based on the format of https://github.com/genome/sciclone-meta/blob/master/tests/data/vafs.dat

After I finish my test, I will give you feedback.

Thanks for your help again!

**Comment by Wan-Yifei** [comment]
Hi Chris,

You are correct. After I merged samples, all clusters can be displayed on the image.

Thanks for your help again. Please close this issue.
