### ISSUE TITLE
Backfilling ref and alt depth for variants only detected in one sample of multi-sample clustering

### ISSUE THREAD

**Issue by kylec** [genome/sciclone#40]
For example, If a variant is only detected in the relapse sample, but not in the primary tumor sample, the code will filter this variant because there's "no" adequate depth in all samples (primary and relapse) as indicated in sciClone.R line 120-123.  

So should I backfill the ref and alt count for this site in the primary sample using a pileup method, so that every sample specific variant will have a ref and alt count and thus could be used in the clustering?

**Comment by chrisamiller** [comment]
Yes, you've got the right idea.  Every variant needs readcounts from every sample. (This is also important because "not called" is not always the same thing as "absent")
