### ISSUE TITLE
How to classify subclone frome sciClone result ?

### ISSUE THREAD

**Issue by bioxu** [genome/sciclone#41]
Hi,
I used sciClone to cluster somatic variants, but don't konw how to classify subclone and founding clone. Do you have any suggestions ? Thank you very much.

**Comment by chrisamiller** [comment]
The founding clone will consist of variants found in the highest-VAF cluster, be in all samples, and all other subclones should be derived from it.  For more on these concepts, you can read the sciclone paper, or the clonevol paper here:  https://pubmed.ncbi.nlm.nih.gov/28950321/
Best of luck!

**Comment by bioxu** [comment]
chrisamiller, thanks for your reply. In my results, there are some samples include more than 6 clusters and the some cluster vaf more than 60 or 80, do you think these clusters also the foudning clone cluster ?

**Comment by chrisamiller** [comment]
Those are almost certainly points from non-copy-number neutral sites. 
There is lots more info on how to exclude those and why it's important both in the paper, and in the questions tagged sciclone at Biostar: https://www.biostars.org/t/sciclone/

**Comment by bioxu** [comment]
Dear Chrisamiller, thank you very much. Do you have some suggestions about the cutoff of VAF in the points from non-copy-number neutral sites? Should these high or low VAF points be discard. Thanks again.
