### ISSUE TITLE
Input purity dara

### ISSUE THREAD

**Issue by tomasellimichelle** [genome/sciclone#42]
Hi, 

I'm working with spatial tumour samples, and I would like to know how I have to input de purity data and inform sciclone to use it. 

Thanks, 
Michelle.

**Comment by chrisamiller** [comment]
The short answer is no, it does not accept purity as an input.  The longer answer can be found in these answers several other issues:
https://github.com/genome/sciclone/issues/21
https://github.com/genome/sciclone/issues/31

You can cluster, and then manually scale your data afterwards, if so desired, for plotting purposes.
