### ISSUE TITLE
Can I still use sciclone?

### ISSUE THREAD

**Issue by beginner984** [genome/sciclone#43]
Hello

I have non matched tumour samples of responders to chemotherapy and non-responders where responders and non-responders are different patients 

I want to know why some patients response and some don't 

as my samples are not matched, can I still use your software?

Thanks

**Comment by chrisamiller** [comment]
The key problem you're going to run into is distinguishing germline mutations from somatic ones. If you can do this reliably, then sciclone will work just fine.  It's hard to do though, and odds are good that you'll end up with a bunch of het germline mutations at 50% VAF in every sample. That's going to confound the clonal analysis.

**Comment by beginner984** [comment]
Thank you, is there any way to get rid of germline mutations in calculation?

**Comment by chrisamiller** [comment]
That is outside the scope of sciClone. There are a variety of techniques to try to recover only somatic events, (such as this one https://genomemedicine.biomedcentral.com/articles/10.1186/s13073-017-0446-9) but all have limitations.  Best of luck!

**Comment by beginner984** [comment]
Sorry, for each patient I have cancer and matched normal samples

Lets say I am 2 groups of patients 

samples collected before any treatment

Samples collected after chemotherapy

These two groups are independent individual I mean For patient A I have either pre or post treatment biopsy

Need for all I have matched normal samples

Can I still use your software for clonal evolution?
