### ISSUE TITLE
Too few clusters

### ISSUE THREAD

**Issue by tomvdbosch** [genome/sciclone#45]
Hi,

I am trying to use SciClone to infer heterogeneity of tumours. I am using the TCGA database for this (10.000+samples), however I only seem to get 1, very rarely 2 clusters for almost all samples. I assume this is incorrect, as in the original SciClone paper the analysis was also done on the TCGA and most examples in this paper actually show 4+ clusters (figure 4a). Also, using the R package Maftools inferHeterogeneity function which uses a similar method actually does give many clusters as output for most samples. Do you have any idea what could cause this? My code is fairly simple:

#
>sciClone(vafs, copyNumberCalls = calls, sampleNames = samp, verbose=FALSE)
# example data:
> vafs[1:10,]
   chromosome  position t_ref t_alt       vaf n_alt_count n_depth
1          10 123810032     4    38 0.8837209           0      74
2          11 124489539   127    89 0.4101382           0     188
3          11  47380512     6     6 0.5000000           0      15
4          11  89868837    34    36 0.5142857           0      81
5          12 107371855    75    53 0.4140625           0     138
6          12 108012011    61    34 0.3578947           0      92
7          12   7980269    43    32 0.4210526           0      93
8          12   8082458   206    28 0.1191489           0     283
9          14 100363606    48    49 0.5051546           0      83
10         14  33290999    75    48 0.3902439           0     121
> calls[1:10,]
       Chromosome     Start       End Segment_Mean
629305          1   3218610  16137774    2.0084743
629306          1  16138059  16138095    0.6436284
629307          1  16142960 180271108    2.0139111
629308          1 180275654 180493841    2.8774682
629309          1 180493944 180494500    5.6768869
629310          1 180495670 180908017    2.9071389
629311          1 180912006 247813706    2.0080567
629312          2    484222 236771407    1.9928042
629313          2 236772143 237408806    2.8661220
629314          2 237410658 242476062    1.9841210

I do this for each sample in a loop instead of all samples in the same data frame, as my computer was unable to work when I tried to run the whole dataset in one go. The mean number of variants in each sample is 210. I have tried changing the copyNumberMargins parameter or leaving out copy numbers alltogether but this does not change much.

The exact files that I used are the broad.mit.edu_PANCAN_Genome_Wide_SNP_6_whitelisted.seg for copy numbers and mc3.v0.2.8.PUBLIC.maf.gz for mutations from https://gdc.cancer.gov/about-data/publications/pancanatlas.

**Comment by chrisamiller** [comment]
That doesn't really surprise me, as much of the TCGA cohort is low-depth sequencing (by modern standards).  

See Figure 5 for for an illustration of how low sequencing depth increases sampling error and makes it very difficult to infer clonality accurately:
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4669575/

One decent sanity check is to plot the data and ask yourself whether you could call clusters by eye that are being missed, or whether the data is really quite noisy/dispersed
