### ISSUE TITLE
Application on targeted NGS data 

### ISSUE THREAD

**Issue by xiw588** [genome/sciclone#50]
Hi, I am trying to apply sciclone to targeted NGS panel data, but seems to be difficult and unreliable. Do you have any insights and suggestions? Thank you!!

**Comment by chrisamiller** [comment]
You'd have to be more specific, but in general, the more mutations that sciclone has to work with, the more reliable the clustering.  In general, targeted panels do not perform well, and deep exome or deep WGS are the most reliable ways to infer clonality.
