### ISSUE TITLE
How to distinguish between clones and subclones

### ISSUE THREAD

**Issue by huerqiang** [genome/sciclone#53]
Hi, thank you so much for developing such a great software! I know that sciclone can divide mutations into multiple clusters(subclone), but it's not clear to me how to distinguish between clones and subclones. Looking forward to your help. Thaks.

**Comment by chrisamiller** [comment]
The short answer is that sciClone just clusters the mutations, interpretation and phylogeny will be up to you, or to downstream software (like clonEvol).  I'd encourage you to read through the questions on bioStars, some of which I think will answer your question more directly: https://www.biostars.org/tag/sciClone/

**Comment by huerqiang** [comment]
Thanks.
