### ISSUE TITLE
Question about the result of sciclone

### ISSUE THREAD

**Issue by huerqiang** [genome/sciclone#54]
Hi, I have some questions about the results when using sciclone for analysis and would like to ask for advice: 
(1) What is the meaning of cluster.means, cluster.upper, and cluster.lower, do they represent the mean, maximum, and minimum VAF values in the cluster?
(2)  I got my vcf file from Mutect2, and the file is simply read as follows:
```r
> head(vcf)
    V1     V2                           V9                                                        V10
1 chr1  69511 GT:AD:AF:DP:F1R2:F2R1:FAD:SB          0/1:0,480:0.997:480:0,175:0,145:0,327:0,0,275,205
2 chr1 930314 GT:AD:AF:DP:F1R2:F2R1:FAD:SB 0/1:288,246:0.448:534:121,97:86,71:212,172:139,149,117,129
3 chr1 941119 GT:AD:AF:DP:F1R2:F2R1:FAD:SB             0/1:0,226:0.994:226:0,97:0,52:0,156:0,0,137,89
4 chr1 942382 GT:AD:AF:DP:F1R2:F2R1:FAD:SB             0/1:115,10:0.056:125:28,3:25,0:96,5:38,77,10,0
5 chr1 942383 GT:AD:AF:DP:F1R2:F2R1:FAD:SB               0/1:120,3:0.03:123:26,0:25,0:100,3:44,76,3,0
6 chr1 942391 GT:AD:AF:DP:F1R2:F2R1:FAD:SB            0/1:132,11:0.063:143:32,3:28,1:106,8:42,90,10,1
```
Could I use the AF value as VAF value? And I found that a large number of AF values are greater than 0.5, and the CCF values calculated from them may be greater than 1. Are these normal?
(3) Can I use CCF values as input for VAF values?

Thank you very much!

**Comment by chrisamiller** [comment]
> What is the meaning of cluster.means, cluster.upper, and cluster.lower

See the help for writeClusterSummaryTable(): 
```
  Creates a table that lists each cluster along with it's mean VAF, and
  the standard error of the mean (high and low)
```

> Could I use the AF value as VAF value

Yes, the AF == VAF

> I found that a large number of AF values are greater than 0.5, and the CCF values calculated from them may be greater than 1. Are these normal?

AFs values greater than 0.5 may be due to a variety of factors (copy number/LOH/sampling error). Poke through the answered questions on biostar for more information: https://www.biostars.org/tag/sciClone/

> Can I use CCF values as input for VAF values?

SciClone will happily cluster any data you throw its way, and CCF values may work. Some of the plotting may not show exactly what you expect, though.

**Comment by huerqiang** [comment]
Thanks.
